# Generated by Django 3.0 on 2019-12-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
