# Generated by Django 3.0 on 2019-12-09 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20191208_1152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
